### PR TITLE
script to generate pkg inspection results against upstream pkgs

### PR DESCRIPTION
**Pull request by taibah**
First working draft of a script to generate inspection HTML formatted report for packages ...

baseos_similar.csv: 1-to-1 mapping for package names (first col is for Rocky pkg names)	
mtpkgcomp.sh: script   
result.htm: report file sample

### CODE REVIEW

**Comment by rlhennig** [comment]
A license file was recently added, and we use BSD3. If you're okay with that, can you please amend your file accordingly?

**Comment by taibah** [comment]
License was updated since this was discussed with Greg last Sunday. Some issue is causing the edited version to fail being modified into this pull request. Looking into it ...

**Comment by taibah** [comment]
Ok, I was able to push ... this should have the latest version with the updated license now

**Review by tcooper — APPROVED** [review]
Thanks for update.

**Pull request merged**
