### PR TITLE
Updating README

### PR DESCRIPTION
**Pull request by StackKorora**
Update dnf package requirements for minimal installs
Remove duplicate './xsos'
Add '-x' flag to prevent color markers from being added into the Git repo.

### CODE REVIEW

**Comment by StackKorora** [comment]
For the second update I noticed the two outputs were different. I like the idea of having a mostly consistent UUID from dmidecode then a random file each time. It might help track changes of the same hardware over time more easily then a randomly generated UUID.

**Comment by tcooper** [comment]
Regarding output file naming I think it's important to keep both examples so people think about the data they are submitting. Perhaps being more explicity about using the same command for the same system will address this without obfuscating? Using `--scrub` removes the dmidecode UUID so if we want to suggest `--scrub` we should reverse that choice by putting the UUID into the filename.

Regarding the package requirement... I'm in favor of leaving out the addition of `device-mapper-multipath`. If the system has multipath devices it will have this installed. If it doesn't it won't and we can ignore the error. I'll need to check on the `pciutils`. I think all my real test machines had it installed but maybe my podman container and VirtualBox vm didn't. I didn't expect those to report anything interesting on the PCI bus so I ignored. What isn't being enumerated on hardware if that's missing that we might want to be tracking?

**Comment by StackKorora** [comment]
I'm fine if we just want to ignore the multipath error. But we should probably make a note that the error can be safely removed. If pciutils is not installed then the system can't run lspci and we lose all of the PCI peripherals which I think are important if we want to capture network cards, gpu's, ect.

**Comment by rlhennig** [comment]
I'll let tcooper merge this one when he's happy with it

**Comment by StackKorora** [comment]
How about this latest update?

**Review by tcooper — APPROVED** [review]
Seems like a reasonable update and without more objection will be merged.

**Pull request merged**
