### PR TITLE
Clean up, updating hierarchy, prep for 9

### PR DESCRIPTION
**Pull request by StackKorora**
## Author checklist (to be completed by original Author)

- [X] I have signed the Rocky Open Source Contributor Agreement (ROSCA).
- [X] I certify this contribution complies with all conditions of the
  [Testing repository contributions guide](./CONTRIBUTING.md)
- [X] If applicable, steps and instructions have been tested to work on a real
  system.
- [X] I have installed pre-commit and all commits in this PR pass.
- [X] If applicable, I have GPG signed all commits and unploaded my private key
  to Github.

---
## Rocky Testing checklist  (to be completed by Rocky team)

- [ ] 1st Pass (Check that contribution is good fit for project and the Testing
  repository is the appropriate location)
- [ ] 2nd Pass (Confirm all pre-commit tests pass)
- [ ] 3nd Pass (Technical Review - check for technical correctness)

### CODE REVIEW

**Comment by StackKorora** [comment]
Merged Lukas' changes - It's much nicer now. Thanks Lukas!

**Review by tcooper — CHANGES_REQUESTED** [review]
@StackKorora 

Most looks good to me.

Possible additional change in `test-reports/container/README.md` to polish the Docker example (originally added by me) to make consistent with changes made to `test-reports/README.md` where the prompts were removed.

Though there is some question in my mind as to what prompts are applicable here to illustrate that some steps are inside the container vs. outside. The last prompt appears to have been edited while the first was likely missed.

I guess I'm suggesting `s/~ > /$ /` on line 8 to remove confusion about where the commands were run.

I can drop on top of this PR within Github UI or you can update in your branch. Do you care which?

**Comment by StackKorora** [comment]
@tcooper Just updated the format. I think this is what you meant. Feel free to comment further. Thanks!

**Review by tcooper — APPROVED** [review]

**Comment by AlanMarshall** [comment]
Looks good to me (for what it's worth).

**Review by AlanMarshall — APPROVED** [review]
Looks good to me.

**Review by akatch — APPROVED** [review]
Looks good, and the process generates the expected output. One non-blocking question I have - what users who built their own systems should use for the manufacturer?

**Pull request merged**
